stages:
- name: pull code
  steps:
  - runScriptConfig:
      image: registry.yz-dev-rrcloud.priv/centos:7.6.1810
      shellScript: echo "hello"
    when:
      event: {}
- name: push image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: registry.yz-dev-rrcloud.priv/jdb-internet/tradeui-php:v1
      pushRemote: true
      registry: 100.73.18.129
    when:
      event: {}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      event: {}
timeout: 60
branch:
  include:
  - master
notification: {}
