stages:
- name: pull code
  steps:
  - runScriptConfig:
      image: registry.yz-dev-rrcloud.priv/centos:7.6.1810
      shellScript: echo "hello"
    when:
      event:
        include:
        - tag
- name: push image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: registry.yz-dev-rrcloud.priv/jdb-internet/tradeui-php:${CICD_GIT_TAG}
      pushRemote: true
      registry: 100.73.18.129
    when:
      event:
        include:
        - tag
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      event:
        include:
        - tag
timeout: 60
branch:
  include:
  - master
notification: {}
